version: '3.9'

services:
  nginx:
    image: nginx:1.19
    ports:
      - "8000:8000"
    volumes:
        - ./nginx/conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: uwsgi --socket :8001 --module instaclone.wsgi
    volumes:
      - .:/code
    expose:
      - "8001"
    depends_on:
      - db