# Generated by Django 3.1.6 on 2021-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
